spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  tomcat:
    # Maintain previous Spring Boot 3.4 behavior (default changed from 'when-available' to 'never' in 3.5)
    use-apr: when-available

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

