spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  tomcat:
    # Maintain previous Spring Boot 3.4 behavior (default changed from 'when-available' to 'never' in 3.5)
    use-apr: when-available


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
